### ISSUE TITLE
Missing openssl.cnf files

### ISSUE THREAD

**Issue by inf0rmer** [jmarhee/docker-swarm-digitalocean-terraform#6]
Hi, thanks for this project!

I was trying to set up a swarm using your project, but it seems that some `*openssl.cnf` template files are missing in the `scripts/` folder. I'm kind of in the dark as to what these files should contain though, so I'd be glad for some help or a pointer in the right direction!

**Comment by jmarhee** [comment]
I've pushed a change that removed that requirement from the scripts, as it was no longer necessary (I can't recall if an earlier version generated these or not, but I assume these referred to the local openssl.cnf on the client machine at some point, which seems to no longer be the case). If you pull down the latest scripts, you shouldn't have any issues moving forward on this. 

But to keep in mind, this script also applies to an older version of Docker; Swarm is now native in more current versions of Docker (as of 1.12), so if you'd prefer, I'd also recommend checking out the native workflow for Swarm mode:

https://docs.docker.com/engine/swarm/swarm-mode/

I may update this repo to use the new methodology, though, if you still wish to use this terraform script, it should still function on current Docker builds available through DO's one-click (which I believe is the image I use in this script)
